env:
  - RELEASE_BUILDS=dist/hopp-cli_darwin_amd64/hopp-cli dist/hopp-cli_linux_386/hopp-cli dist/hopp-cli_linux_amd64/hopp-cli dist/hopp-cli_windows_386/hopp-cli.exe dist/hopp-cli_windows_amd64/hopp-cli.exe
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.buildVersion={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
    hooks:
      post: make pack-releases
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: hoppscotch
    name: hopp-cli
brews:
  - name: hopp-cli
    github:
      owner: athul
      name: homebrew-tap
    folder: Formula
    homepage: 'https://github.com/hoppscotch/hopp-cli'
    description: 'CLI for Hoppscotch.io'
    install: bin.install "hopp-cli"
